# Generated by Django 3.2 on 2022-09-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_auto_20220923_1528"),
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagefile",
            options={"ordering": ["position", "created_on"]},
        ),
        migrations.AddField(
            model_name="imagefile",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="places.place",
            ),
        ),
        migrations.AddField(
            model_name="imagefile",
            name="position",
            field=models.IntegerField(default=1),
        ),
    ]
