# Generated by Django 3.2 on 2022-09-23 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_remove_place_imgs"),
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagefile",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="places.place",
            ),
        ),
    ]
