# Generated by Django 4.1.1 on 2022-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0002_auto_20220923_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefile",
            name="position",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
