# Generated by Django 3.2 on 2022-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0002_imagefile_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagefile",
            options={"ordering": ["position", "created_on"]},
        ),
        migrations.AddField(
            model_name="imagefile",
            name="position",
            field=models.IntegerField(default=1),
        ),
    ]
