# Generated by Django 3.2 on 2022-09-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
