# Generated by Django 3.2 on 2022-09-23 07:16

import djgeojson.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_place_imgs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="coordinates",
        ),
        migrations.AddField(
            model_name="place",
            name="coordinates_2",
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
