# Generated by Django 3.2 on 2022-09-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_auto_20220923_0716"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="coordinates_2",
            new_name="geom",
        ),
    ]
