# Generated by Django 3.2 on 2022-09-23 07:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_coordinates_2_place_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='geom',
        ),
        migrations.AddField(
            model_name='place',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
